[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_API_BASE_URL = "https://aipcn.onrender.com"
  VITE_APP_NAME = "AIPC Healthcare Platform"
  VITE_DEMO_MODE = "true"

[[redirects]]
  from = "/api/*"
  to = "https://aipcn.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
