services:
  - type: web
    name: aipc-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node basic-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
